### ISSUE TITLE
Autowiring not working

### ISSUE THREAD

**Issue by cdesign** [endroid/pdf#1]
This may be me, but I started with a fresh install of Symfony 4.0.10 and ran

`composer require endroid/pdf`

But then when I list services with `php bin/console debug:container` or `php bin/console debug:autowiring`, there is no PdfBuilder, Pdf, or Snappy service. What am I doing wrong?

**Comment by endroid** [comment]
Hi @cdesign what version of the endroid/pdf library did composer install exactly (see composer.lock)? When I run "bin/console debug:container | grep Pdf" I see both the Pdf and builder service. Did it install the endroid/installer and knplabs/knp-snappy library and do you see config/packages/endroid_pdf.yaml file and do the contents of that file match https://github.com/endroid/pdf/blob/master/.install/symfony/config/packages/endroid_pdf.yaml? And could you try running the debug:container command with --show-private?

**Comment by cdesign** [comment]
Thx for reply! From composer.lock (see below):

- endroid/pdf  v1.0.7
- knplabs/knp-snappy  v1.0.4

but I don't see any 'endroid/installer.

And no, it did not copy the endroid_pdf.yaml to config/packages.

And `debug:container | grep Pdf` gives me nothing :( even with the --show-private option on.

**Comment by cdesign** [comment]
[composer.lock.txt](https://github.com/endroid/pdf/files/2041018/composer.lock.txt)

**Comment by endroid** [comment]
Hi @cdesign I see the endroid/installer was nog present in the 1.0.7 version. I now tagged the latest version as 1.0.8. Can you try that one and see if the yaml files are copied correctly? Thank you.

**Comment by cdesign** [comment]
Ok.. after runnning `composer.phar update` I now have 'endroid_asset.yaml' and 'endroid_pdf.yaml' files in config/packages folder. And I see the following two private services:

`Endroid\Pdf\Builder\PdfBuilder`
`Endroid\Pdf\Pdf`

But no 'snappy' service. And when I add this to my controller:

```
    private $pdfBuilder;

    public function __construct(PdfBuilder $pdfBuilder)
    {
        $this->pdfBuilder = $pdfBuilder;
    }
```

I get the following runtime exception:

```Cannot autowire service "Endroid\Pdf\Pdf": argument "$snappy" of method "__construct()" references class "Knp\Snappy\Pdf" but no such service exists.```

Do I have to register snappy manually?

**Comment by cdesign** [comment]
This appears to be either a missing Endroid/Snappy config param or that Snappy needs to be registered 'manually.' If I add the following to services.yaml it works:
```
    Knp\Snappy\Pdf:
        arguments: ['../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64']
```
Otherwise the Snappy 'binary' param gets set to null and the pdf cannot be generated because wkhtmltopdf can't be found.

**Comment by endroid** [comment]
Cool, thanks for finding out. I was working with the snappy bundle which does this already so I didn't notice. I will see if I can support both cases.
