### ISSUE TITLE
Missing Twig Extension?

### ISSUE THREAD

**Issue by cdesign** [endroid/pdf#2]
I am getting a twig syntax error ('Unknown "embed" function') when I attempt to use the following line in twig:
```
@font-face {
            font-family: 'FuturaLight';
            src: url('{{ embed('/fonts/FuturaPT/FuturaPT-Light.ttf') }}' );
        }
```
I don't see the 'embed' function defined anywhere in endroid/pdf. Did it perhaps get left out? I am using, 1.0.8?

thx much!

**Comment by endroid** [comment]
You're right. I refactored it out of the PDF library but forgot to require it. Should work in 1.0.9.
