### ISSUE TITLE
use of ControllerAsset

### ISSUE THREAD

**Issue by zogs** [endroid/pdf#4]
Hello,
I managed to install your library (without autoring) and it is working great at some levels. but i can't understand how to use the ControllerAsset. What is the typical usecase ? Can i call a specific method ? What is the expected return ?

Thank you and have good day !

**Comment by endroid** [comment]
Hi @zogs you can find some more information about the asset package [here](https://github.com/endroid/asset). You can use the asset factory as described there or you can check the [ControllerAsset class](https://github.com/endroid/asset/blob/master/src/ControllerAsset.php).
